trigger:
 paths:
    include:
      - static

pool:
 name: my_agent_pool

variables:
  dockerRegistryServiceConnection: 'ACR_service_conn'
  imageRepository: 'goapp'
  containerRegistry: 'trinayacr.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  storageaccount: 'agentsc'
  resourcegroup: 'cicd_rg'
  sacontainername: 'trivy-scan-reports'
  serviceconn: 'newServiceConnection'
  target: $(build.artifactstagingdirectory)
  artifact: TRI

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: GoTool@0
      inputs:
        version: '1.20'
    - script: go build -o go-web-app
      displayName: Build Go Web Application

- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Test
    steps:
    - task: GoTool@0
      inputs:
        version: '1.20'
    - script: go test ./...
      displayName: Run Go Tests
      
- stage: CodeAnalysis
  displayName: Code Analysis
  jobs:
  - job: CodeAnalysis
    displayName: Code Analysis
    steps:
    - task: SonarQubePrepare@7
      displayName: Prepare Analysis Configuration
      inputs:
        SonarQube: 'sonar_conn'
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'my_project'
        cliProjectName: 'CICD-sonar'
        cliSources: '.'
        extraProperties:
          sonar.go.binaries=.

    - task: SonarQubeAnalyze@7
      displayName: Run Code Analysis
      
    - task: SonarQubePublish@7
      displayName: Publish Sonar Results
      inputs:
        pollingTimeoutSec: '300'

- stage: BuildImage
  displayName: Build Image
  jobs:
  - job: BuildImage
    displayName: Build Image
    steps:
    - task: Docker@2
      displayName: Build Image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'build'
        dockerfile: '$(dockerfilePath)'
        tags: '$(tag)'
        
- stage: Push
  displayName: Push
  jobs:
  - job: Push
    displayName: Push
    steps:
    - task: Docker@2
      displayName: Push
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'

- stage: InstallTrivy
  displayName: InstallTrivy
  jobs:
  - job: InstallTrivy
    displayName: InstallTrivy
    steps:
    - task: CmdLine@2
      displayName: DOWNLOAD AND INSTALL AQUASEC TRIVY
      inputs:
        script: |
         sudo apt-get install wget apt-transport-https gnupg lsb-release
         wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
         echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
         sudo apt-get update
         sudo apt-get install trivy
         trivy -v
         pwd

- stage: RunTrivyScan
  displayName: RunTrivyScan
  jobs:
  - job: RunTrivyScan
    displayName: RunTrivyScan
    steps:
    - task: CmdLine@2
      displayName: RUN AQUASEC TRIVY SCAN AND COPY TO ARTIFACTS STAGING DIRECTORY
      inputs:
        script: |
          trivy image --exit-code 0 --severity LOW,MEDIUM $(containerRegistry)/$(imageRepository):$(tag) > low-med.txt
          trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$(imageRepository):$(tag) > high-critical.txt
          ls -l
          cp -rvf *.txt $(target)

- stage: PublishArtifacts
  displayName: PublishArtifacts
  jobs:
  - job: PublishArtifacts
    displayName: PublishArtifacts
    steps:
    - task: PublishBuildArtifacts@1
      displayName: PUBLISH ARTIFACTS
      inputs:
        targetPath: '$(target)'
        artifactName: '$(artifact)'

- stage: DownloadArtifacts
  displayName: DownloadArtifacts
  jobs:
  - job: DownloadArtifacts
    displayName: DownloadArtifacts
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: DOWNLOAD ARTIFACTS
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'

- stage: UploadScanReports
  displayName: UploadScanReports
  jobs:
  - job: UploadScanReports
    displayName: UploadScanReports
    steps:
    - task: AzureCLI@1
      displayName: UPLOAD AQUASEC TRIVY SCAN REPORTS TO BLOB STORAGE
      inputs:
        azureSubscription: '$(serviceconn)'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az storage blob upload-batch -d $(sacontainername)/$(date "+%d-%m-%Y_%H-%M-%S") --account-name $(storageaccount) --account-key $(az storage account keys list -g $(resourcegroup) -n $(storageaccount) --query [0].value -o tsv) -s $(System.ArtifactsDirectory)/TRI

- stage: UpdateManifests
  displayName: UpdateManifests
  jobs:
  - job: UpdateManifests
    displayName: UpdateManifests
    steps:
    - task: ShellScript@2
      displayName: UPDATE K8S MANIFESTS WITH THE NEW IMAGE
      inputs:
        scriptPath: 'scripts/updateK8sManifests.sh'
        args: 'vote $(imageRepository) $(tag)'
